// crea una matriz con varios textos que se alternarán
var textos = ['"Cada fracaso es una oportunidad para comenzar de nuevo con más experiencia." - Henry Ford', 
'"El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito." - Albert Schweitzer',
'"El éxito es ir de fracaso en fracaso sin perder el entusiasmo." - Winston Churchill', 
'«No hay nada imposible, la palabra misma dice "soy posible"». - Audrey Hepburn',
'"Elige un trabajo que te guste, y nunca tendrás que trabajar ni un solo día de tu vida." - Confucio', 
'"No te rindas, cada fracaso es una oportunidad para comenzar de nuevo, con más experiencia." - Anónimo',
'"La felicidad no es algo hecho. Viene de tus propias acciones." - Dalai Lama', 
'"La motivación es lo que te hace comenzar. El hábito es lo que te mantiene avanzando." - Jim Ryun',
'"Nunca es demasiado tarde para ser lo que podrías haber sido." - George Eliot', 
'"La única forma de hacer un gran trabajo es amar lo que haces." - Steve Jobs',
'"No se trata de lo que te pasa, sino de cómo reaccionas ante lo que te pasa." - Epicteto', 
'"El miedo es la emoción más dañina que existe. Te impide actuar, te paraliza y te aleja de tus objetivos." - Anónimo',
'"No juzgues a nadie sin conocer su historia." - Anónimo', '"Si no haces nada diferente, nada diferente pasará." - Anónimo',
'"El odio no disminuye con el odio, el odio disminuye con el amor." - Buda',
'"No podemos cambiar el viento, pero sí ajustar las velas." - Proverbio',
'"No hay nada más peligroso que la verdad en un mundo que miente." - Anónimo',
'"El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito." - Albert Schweitzer',
'"El dolor es inevitable, pero el sufrimiento es opcional." - Buda',
'"El que tiene un porqué para vivir se puede enfrentar a cualquier cómo." - Friedrich Nietzsche',
'"No busques la felicidad fuera, está en tu interior. Sólo tienes que descubrirla." - Anónimo',
'"La única forma de hacer un buen trabajo es amar lo que haces." - Steve Jobs',
'"La verdad es como una piedra en un camino: todos la ven, pero pocos la levantan." - Anónimo',
'"No mires hacia atrás a menos que tengas la intención de ir en esa dirección." - Henry David Thoreau',
'"El éxito no es el resultado de una sola cosa, sino del equilibrio de muchas cosas." - Anónimo',
'"A veces tienes que dar un paso atrás para dar dos adelante." - Anónimo',
'"El valor no es la ausencia de miedo, sino la decisión de seguir adelante a pesar del miedo." - Nelson Mandela',
'"La felicidad no es tener lo que quieres, sino querer lo que tienes." - Anónimo',
'"No esperes a tenerlo todo para disfrutar de la vida, disfruta de lo que tienes mientras trabajas por lo que quieres." - Anónimo',
'"La libertad no es hacer lo que queremos, sino querer lo que debemos hacer." - Jean-Jacques Rousseau',
'"La educación es el arma más poderosa que puedes usar para cambiar el mundo." - Nelson Mandela',
'"La música es el lenguaje universal de la humanidad." - Henry Wadsworth Longfellow',
'"El deporte no construye el carácter, lo revela." - Heywood Broun',
'"La risa es la mejor medicina." - Anónimo',
'"La creatividad es la inteligencia divirtiéndose." - Albert Einstein',
'"La tecnología es sólo una herramienta. En términos de conseguir las cosas hechas, no es tanto como la gente piensa." - Steve Jobs',
'"La vida es como una bicicleta, para mantener el equilibrio hay que seguir adelante." - Albert Einstein',
'"La paciencia es amarga, pero sus frutos son dulces." - Jean-Jacques Rousseau',
'"La belleza es cómo te sientes por dentro, y se refleja en tus ojos. No es algo físico." - Sophia Loren',
'"El éxito en los negocios requiere entrenamiento y disciplina y trabajo duro. Pero si no estás asustado por estos detalles, las oportunidades son simplemente fantásticas." - David Rockefeller',
'"La literatura es una forma de explorar y entender el mundo que nos rodea." - Anónimo',
'"El cine es una forma de arte que te permite contar historias con imágenes y sonidos." - Anónimo',
'"La ciencia es el conocimiento organizado de la realidad." - Edward O. Wilson',
'"La comida es el ingrediente que une a la gente." - Anónimo',
'"El arte es la expresión del alma humana." - Anónimo',
'"La justicia social es la igualdad de oportunidades y derechos para todas las personas." - Anónimo',
'"La política es el arte de lo posible." - Otto von Bismarck',
'"La religión es una forma de encontrar significado y propósito en la vida." - Anónimo',
'"La filosofía es la búsqueda de la sabiduría y la comprensión profunda de la vida." - Anónimo'];

var randomIndex = Math.floor(Math.random() * texts.length);
		var randomText = texts[randomIndex];

		document.getElementById("randomText").innerHTML = randomText;